[package]
name = "lnm-sdk"
authors = ["Rafael Lemos <contact@flemosr.com"]
version = "0.1.0"
edition = "2024"
license = "UNLICENSED"
publish = false

[dependencies]
async-trait = "0.1.88"
chrono = { version = "0.4.40", features = ["now", "serde"] }
fastwebsockets = { version = "0.10.0", features = ["upgrade"] }
hex = "0.4.3"
http-body-util = "0.1.3"
hyper = "1.6.0"
hyper-util = { version = "0.1.11", features = ["tokio"] }
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
tokio-rustls = "0.26.2"
webpki-roots = "0.26.8"
