[package]
name = "quantoxide"
authors = ["Rafael Lemos <contact@flemosr.com"]
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"
publish = false

[dependencies]
chrono = { version = "0.4.40", features = ["now", "serde"] }
fastwebsockets = { version = "0.10.0", features = ["upgrade"] }
hex = "0.4.3"
http-body-util = { version = "0.1.3" }
hyper = { version = "1.6.0" }
hyper-util = { version = "0.1.10", features = ["tokio"] }
lazy_static = "1.5.0"
rand = "0.9.0"
reqwest = { version = "0.12.12", features = ["json"] }
sqlx = { version = "0.8.3", features = [
    "chrono",
    "migrate",
    "postgres",
    "runtime-tokio",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tokio-rustls = "0.26.2"
webpki-roots = "0.26.8"
async-trait = "0.1.88"
