[package]
name = "analysis"
authors = ["Rafael Lemos <contact@flemosr.com"]
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"
publish = false

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio", "postgres"] }
